package de.symeda.sormas.api;

import de.symeda.sormas.api.i18n.I18nProperties;

public enum FormType {
    CASE_CREATE,
    CASE_EDIT,
    PERSON_EDIT,
    HOSPITALIZATION_EDIT,
    SYMPTOMS_EDIT,
    EPIDEMIOLOGICAL_EDIT,
    RISK_FACTOR_EDIT,
    FOOD_HISTORY_EDIT,
    SIXTY_DAY_FOLLOW_UP_EDIT,
    AFP_IMMUNIZATION_EDIT,
    FOOD_SAMPLE_TESTING_EDIT,
    PERSON_LOCATION_EDIT,
    SAMPLE_CREATE,
    SAMPLE_EDIT,
    PATHOGEN_TEST_CREATE,
    PATHOGEN_TEST_EDIT,
    TASK_EDIT,
    CLINICAL_VISIT_EDIT,
    HEALTH_CONDITION_EDIT,
    PRESCRIPTION_EDIT,
    TREATMENT_EDIT,
    IMMUNIZATION_EDIT,
    VACCINATION_EDIT,
    CONTACT_EDIT,
    PORT_HEALTH_INFO_EDIT,
    MATERNAL_HISTORY_EDIT,
    EVENT_EDIT,
    EPI_LOCATION_EDIT,
    INVESTIGATION_NOTES_EDIT,
    FOLLOW_UP_VISITS;

    @Override
    public String toString() {
        return I18nProperties.getEnumCaption(this);
    }
}
