pipeline{
    agent any

    stages {
    stage('build') {
      steps {
        echo 'Building .....'
      }
    }
    stage('maven clean') {
      steps {
        withMaven() {
      bat 'mvn -f ./sormas-base/pom.xml clean'
        }
      }
    }
    stage('maven install') {
      steps {
        withAnt() {
      bat 'ant -noinput -buildfile ./sormas-base/build.xml install'
        }
      }
    }
    stage('maven collect-all') {
      steps {
        withAnt() {
      bat 'ant -noinput -buildfile ./sormas-base/build.xml collect-all'
        }
      }
    }
    stage('test') {
      steps {
        echo 'Testing .....'
      }
    }
    stage('deploy') {
      steps {
        echo 'Deploying .....'
        echo 'Done .....'
      }
    }
  }
}