pipeline{
    agent any
    environment {
        M2_HOME = "/root/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.8.6"
    }

    stages {
    stage('build') {
      steps {
        echo 'Building ....'
      }
    }
    stage('maven clean') {
      steps {
        withMaven(maven: 'Maven_3.8.6') {
      sh 'mvn -f ./sormas-base/pom.xml clean'
        }
      }
    }
    stage('maven install') {
      steps {
        withMaven(maven: 'Maven_3.8.6') {
      sh 'mvn -f ./sormas-base/pom.xml clean install -U -DskipTests'
        }
      }
    }
    stage('Ant Deploy serverlibs') {
      steps {
        withAnt(installation: 'Ant_1.10.12') {
      sh 'ant -noinput -buildfile ./sormas-base/build.xml deploy-serverlibs'
        }
      }
    }
    stage('Gradle generate apk') {
      steps {
        withGradle {
      sh ' cd sormas-app && ./gradlew assembleDebug'
        }
      }
    }
    stage('maven collect-all') {
      steps {
        withAnt(installation: 'Ant_1.10.12') {
      sh 'ant -noinput -buildfile ./sormas-base/build.xml collect-all'
        }
      }
    }
    stage('test') {
      steps {
        echo 'Testing .....'
      }
    }
    stage('deploy') {
      steps {
        echo 'Deploying .....'
        echo 'Done .....'
      }
    }
  }
}